### ISSUE TITLE
When "About FestU" is active in the menubar, all links are marked as active.

### ISSUE THREAD

**Issue by angseus** [angseus/festu.se#12]
![screen shot 2016-08-18 at 10 12 23](https://cloud.githubusercontent.com/assets/6103061/17766626/520ea210-652c-11e6-8b1d-75de2dc2c546.png)
![screen shot 2016-08-18 at 10 12 22](https://cloud.githubusercontent.com/assets/6103061/17766625/520e2902-652c-11e6-9b9a-fc40c2dbbe44.png)

**Comment by marcushultman** [comment]
dis has nao been fixed!
